environment:
  AV_PROJECTS: 'c:\projects'
  AV_OME_M2: 'c:\projects\m2'
  AV_OME_PYTHON: 'c:\projects\python'
  AV_OME_SOURCE: 'c:\projects\source'

# Note that only Oracle JDK is provided.
  matrix:
    - java: 10
    - java: 1.8
    - java: 1.7

cache:
  - '%AV_OME_M2% -> appveyor.yml'
  - '%AV_OME_PYTHON% -> appveyor.yml'

os: 'Visual Studio 2015'
clone_folder: '%AV_OME_SOURCE%'
clone_depth: 5
platform: x64

init:
  - git config --global core.autocrlf input
  - refreshenv
  - 'if [%java%] == [1.7] set "JAVA_HOME=C:\Program Files\Java\jdk1.7.0"'
  - 'if [%java%] == [1.8] set "JAVA_HOME=C:\Program Files\Java\jdk1.8.0"'
  - 'if [%java%] == [10] set "JAVA_HOME=C:\Program Files\Java\jdk10"'
  - PATH=%JAVA_HOME%\bin;%PATH%
  - 'set "MAVEN_OPTS=-Dmaven.repo.local=%AV_OME_M2%"'
  - 'if [%java%] == [1.7] set "MAVEN_OPTS=%MAVEN_OPTS% -Dhttps.protocols=TLSv1.2"'

build_script:
  # Cached venv is available from this point.
  - 'if NOT EXIST "%AV_OME_PYTHON%\" set AV_OME_CREATE_VENV=true'
  - 'if [%AV_OME_CREATE_VENV%] == [true] C:\Python27-x64\python -m pip install virtualenv'
  - 'if [%AV_OME_CREATE_VENV%] == [true] C:\Python27-x64\python -m virtualenv %AV_OME_PYTHON%'
  - PATH=%AV_OME_PYTHON%;%AV_OME_PYTHON%\scripts;%PATH%
  - 'if [%AV_OME_CREATE_VENV%] == [true] python -m pip install sphinx'
  - mvn install
