---
language: java

sudo: false

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk11
  - openjdk8

env:
  - MAVEN_OPTS=-Dpython=python3
  - MAVEN_OPTS=-Dpython=python2

matrix:
  fast_finish: true

before_install:
  - python2 --version
  - python3 --version
  - pip install --user -r requirements.txt
